repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-byte-order-marker
    - id: check-added-large-files
    - id: check-shebang-scripts-are-executable
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.1
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/python-poetry/poetry
  rev: 1.7.1
  hooks:
    - id: poetry-check
    - id: poetry-lock
