model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
  - model_name: phi
    litellm_params:
      model: ollama/phi
litellm_params:
  drop_params: True
