model_list:
  - model_name: phi # Route requests intended for the `phi` model to `tinydolphin` instead since only `phi` option (not `tinydolphin`) is available in `src/discord_bot/bot.py` 
    litellm_params:
      model: ollama/tinydolphin

litellm_params:
  drop_params: True

router_settings:
  num_retries: 2
  timeout: 60                       # seconds
