name: Build and publish the Ollama test server with Tinydolphin model

on:
 - push

jobs:
  build_dev_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.test_ollama
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}/ollama-tinydolphin-preloaded:latest
            ghcr.io/${{ github.repository }}/ollama-tinydolphin-preloaded:${{ github.sha }}
