name: Build the container image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - src/**
      - bin/**
      - pnpm-lock.yaml
      - package.json
      - .github/workflows/build.yml

jobs:
  test-and-lint:
    uses: ./.github/workflows/workflow-test-and-lint.yml
  deploy:
    needs: test-and-lint
    uses: ./.github/workflows/workflow-build.yml
