name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Lint with Ruff
        run: poetry run ruff check .

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Format check with Ruff
        run: poetry run ruff format --check .

  pytest:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ghcr.io/bifrostlab/llm-assistant/ollama-tinydolphin-preloaded
        ports:
          - 11434:11434
      litellm:
        image: ghcr.io/berriai/litellm:main-v1.29.1
        ports:
          - 4000:4000
        volumes:
          - ./tests/setup:/config
        options: --port 4000 --config /config/config.json
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Run pytest
        run: poetry run pytest tests/

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Typecheck with mypy
        run: poetry run mypy .
