name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Lint with Ruff
        run: poetry run ruff check .

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Format check with Ruff
        run: poetry run ruff format --check .

  pytest:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ghcr.io/bifrostlab/llm-assistant/ollama-tinydolphin-preloaded
        ports:
          - 11434:11434
    steps:
      - uses: actions/checkout@v4

      - name: Setup LiteLLM proxy
        run: docker run -d -p 4000:4000 -v ./tests/litellm_config.yaml:/app/proxy_server_config.yaml --name litellm ghcr.io/berriai/litellm:main-v1.29.1

      - name: List the docker containers
        run: docker ps

      - name: Test the ollama container
        run: curl http://localhost:11434/api/generate -d '{"model":"tinydolphin","prompt":"Hello, world!","stream":false}'

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Run pytest
        run: poetry run pytest tests/

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Typecheck with mypy
        run: poetry run mypy .
